<?php

namespace GenericBundle\Repository;

/**
 * CompteRenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRenduRepository extends \Doctrine\ORM\EntityRepository
{
}
