<?php

namespace GenericBundle\Repository;

/**
 * ImportCandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportCandidatRepository extends \Doctrine\ORM\EntityRepository
{
}
