<?php

namespace GenericBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use \Doctrine\ORM\EntityRepository;

class TierRepository extends EntityRepository
{
    public function findAllExcept($id)
    {
        $qb = $this->getEntityManager()->createQuery("SELECT t FROM GenericBundle:Tier t WHERE t.id != $id");

        return $qb->getResult();
    }
}