metier_user_admin:
    path : /
    defaults: { _controller: AdminBundle:Default:load}

metier_user_licenceadded:
    path : /licenceadded
    defaults: { _controller: AdminBundle:LicenceDef:licenceadded}

admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: AdminBundle:LicenceDef:affichageLicence}

metier_user_associated:
    path:  /associated
    defaults: { _controller: AdminBundle:LicenceDef:associated}

loadgestionQCM:
    path:     /gestionQCM/{id}
    defaults: { _controller: AdminBundle:QCM:load, id :ajouter }

Add_QCM:
    path: /addQCM
    defaults: { _controller: AdminBundle:QCM:add }

supprimer_QCM:
    path: /supprimerQCM/rep={rep}&qst={qst}&qcm={qcm}
    defaults: { _controller: AdminBundle:QCM:supprimer }

userModif:
    path: /userModif
    defaults: { _controller: AdminBundle:User:userModif}

supprimerQCM:
    path: /supprimerQCM/nom={nom}
    defaults: { _controller: AdminBundle:QCM:deleteQcm}

creeNewModele:
    path: /creeNewModele/id={id}
    defaults: { _controller: AdminBundle:Default:creeNewModele, id :ajouter}

saveNewModele:
    path: /saveNewModele
    defaults: { _controller: AdminBundle:Default:saveNewModele}