metier_user_admin:
    path : /
    defaults: { _controller: AdminBundle:Default:load}

checkExist:
    path : /checkExist
    defaults: { _controller: AdminBundle:Ecole:checkExist}

tieradded:
    path : /added
    defaults: { _controller: AdminBundle:Ecole:tieradded}

metier_user_licenceadded:
    path : /licenceadded
    defaults: { _controller: AdminBundle:LicenceDef:licenceadded}

metier_user_affiche:
    path: /affichage/id={id}
    defaults: { _controller: AdminBundle:Default:affichage}



admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: AdminBundle:LicenceDef:affichageLicence}

metier_user_associated:
    path:  /associated
    defaults: { _controller: AdminBundle:LicenceDef:associated}

supprimer_Licence:
    path:  /suppLicence/{id}
    defaults: {_controller: AdminBundle:Ecole:suppLicence}

loadgestionQCM:
    path:     /gestionQCM/{id}
    defaults: { _controller: AdminBundle:QCM:load, id :ajouter }

Add_QCM:
    path: /addQCM
    defaults: { _controller: AdminBundle:QCM:add }

supprimer_QCM:
    path: /supprimerQCM/rep={rep}&qst={qst}&qcm={qcm}
    defaults: { _controller: AdminBundle:QCM:supprimer }

ecoles_assiciated:
    path: /ecolesassociated/id={id}
    defaults: { _controller: AdminBundle:Ecole:ecolesassociated}

modifieretab:
    path: /modifieretablissement/{id}
    defaults: { _controller: AdminBundle:Ecole:modifier}

etabmodif:
    path: /etabmodif
    defaults: { _controller: AdminBundle:Ecole:etabModif}

userModif:
    path: /userModif
    defaults: { _controller: AdminBundle:User:userModif}

supprimerQCM:
    path: /supprimerQCM/nom={nom}
    defaults: { _controller: AdminBundle:QCM:deleteQcm}

creeNewModele:
    path: /creeNewModele/id={id}
    defaults: { _controller: AdminBundle:Default:creeNewModele, id :ajouter}

saveNewModele:
    path: /saveNewModele
    defaults: { _controller: AdminBundle:Default:saveNewModele}

supprimerAssociationEcole:
    path: /suppressionAssociationEcole/{id_ecole}/{id_liee}
    defaults: { _controller: AdminBundle:Ecole:suppEcoleAssoc}

mission_added:
    path: /mission_added
    defaults: { _controller: AdminBundle:Ecole:addMission}
admin_afficheMission:
            path: /affichageMission/id={id}
            defaults: { _controller: AdminBundle:Ecole:affichageMission}