apprenant:
    resource: "@ApprenantBundle/Resources/config/routing.yml"
    prefix:   /apprenant/

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix:   /Mission/

tier:
    resource: "@TierBundle/Resources/config/routing.yml"
    prefix:   /tier/

societe:
    resource: "@SocieteBundle/Resources/config/routing.yml"
    prefix:   /societe/

ecole:
    resource: "@EcoleBundle/Resources/config/routing.yml"
    prefix:   /ecole/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

generic:
    resource: "@GenericBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"