supprimer_Mission:
    path:  /suppMission/{id}
    defaults: {_controller: MissionBundle:Default:suppMission}

mission_added:
    path: /mission_added
    defaults: { _controller: MissionBundle:Default:addMission}

missionModif:
    path: /missionModif
    defaults: { _controller: MissionBundle:Default:missionModif}


Diffuser_Mission:
    path: /DiffuserMission/id={id}
    defaults: { _controller: MissionBundle:Default:DiffuserMission}

Afficher_Mission_Propose:
    path: /MissionPropose/id={id}
    defaults: { _controller: MissionBundle:Default:AfficherMissionPropose}

Valider_Diffusion:
    path: /ValiderDiffusion/id={id}
    defaults: { _controller: MissionBundle:Default:ValiderDiffusion}

postuler_Mission:
    path: /postuler/id={id}
    defaults: { _controller: MissionBundle:Default:Postuler}

Assigner_tuteur:
    path: /assignertuteur/id={id}
    defaults: { _controller: MissionBundle:Default:AssignerTuteur}

admin_afficheMission:
    path: /affichageMissionForm/id={id}/idFor={idFor}
    defaults: { _controller: MissionBundle:Default:affichageMissionForm}

ModifierStatutMission:
    path: /ModifStatutMission/id={id}/statut={statut}
    defaults: { _controller: MissionBundle:Default:ModifStatutMission}




