admin_afficheMission:
    path: /affichageMission/id={id}
    defaults: { _controller: MissionBundle:Default:affichageMission}

supprimer_Mission:
    path:  /suppMission/{id}
    defaults: {_controller: MissionBundle:Default:suppMission}

mission_added:
    path: /mission_added
    defaults: { _controller: MissionBundle:Default:addMission}

modifierMission:
    path: /modifierMiss/{id}
    defaults: { _controller: MissionBundle:Default:modifier}

missionModif:
    path: /missionModif
    defaults: { _controller: MissionBundle:Default:missionModif}


MettreEnRelation_added:
    path: /MettreEnRelation_added
    defaults: { _controller: MissionBundle:Default:addMettreEnRelation}
