afficher_rendezvous:
    path: /afficher_rendezvous
    defaults: { _controller: UserBundle:Default:afficher_rendezvous }

afficher_MiseEnRelation:
    path: /afficher_MiseEnRelation
    defaults: { _controller: UserBundle:Default:affichageMiseEnRelation }

afficher_MissionPropose:
    path: /afficher_MissionPropose
    defaults: { _controller: UserBundle:Default:affichageMissionPropose }

afficher_ApprenantPropose:
    path: /afficher_ApprenantPropose
    defaults: { _controller: UserBundle:Default:affichageApprenantPropose }

DateRDV:
    path: /choix_Date_RDV/idrdv={id}/numeroDate={numero}}
    defaults: { _controller: UserBundle:MiseEnRelation:choixDate }

AnnulerRDV:
    path: /AnnulerRDV/idrdv={id}
    defaults: { _controller: UserBundle:MiseEnRelation:annulerRDV }

CompteRenduSaisie:
    path: /CompteRendu/idrdv={id}/{Type}
    defaults: { _controller: UserBundle:MiseEnRelation:CompteRenduSaisie }

AjournementRDV:
    path: /Ajournement/idrdv={id}/{DateTimeRdv}
    defaults: { _controller: UserBundle:MiseEnRelation:Ajournement }

AcceptRDVTuteur:
    path: /accept_tuteur_RDV/idrdv={id}/numeroDate={numero}/textRDV={textmessage}
    defaults: { _controller: UserBundle:MiseEnRelation:AcceptRDVTuteur }

AjournementRDVTuteur:
    path: /AjournementTuteur/idrdv={id}/{DateTimeRdv}
    defaults: { _controller: UserBundle:MiseEnRelation:AjournementTuteur }

AnnulerRDVTuteur:
    path: /AnnulerRDVTuteur/idrdv={id}
    defaults: { _controller: UserBundle:MiseEnRelation:annulerRDVTuteur }

RelancerApp:
    path: /RelancerApprenant/idApp={idApp}/idMission={idMission}
    defaults: { _controller: UserBundle:MiseEnRelation:RelancerApprenant }

Relancer_Tuteur:
    path: /RelancerTuteur/idTuteur={idTuteur}/idMission={idMission}/idApp={idApp}
    defaults: { _controller: UserBundle:MiseEnRelation:RelancerTuteur }

AccepterApp:
    path: /AccepterApprenant/idApp={idApp}idMission={idMission}
    defaults: { _controller: UserBundle:MiseEnRelation:AccepterApprenant }

RefuserApp:
    path: /RefuserApprenant/idApp={idApp}idMission={idMission}
    defaults: { _controller: UserBundle:MiseEnRelation:RefuserApprenant }