expired:
    path: /admin/expired/id={id}
    defaults: { _controller: UserBundle:Default:expired}

userModif:
    path: /userModif
    defaults: { _controller: UserBundle:Default:userModif}

metier_user_afficheUser:
    path: /admin/affichageUser/id={id}
    defaults: { _controller: UserBundle:Default:affichageUser}

user_added:
    path:  /admin/Useradded
    defaults: {_controller: UserBundle:Default:UserAdded}

supprimerUtilisateur:
    path : /admin/supprimeruser/id={id}
    defaults: { _controller: UserBundle:Default:supprimeruser}

modifierUser:
    path: /admin/modifierUtilisateur/{id}
    defaults: { _controller: UserBundle:Default:modifier}

import:
    path: /admin/import
    defaults: { _controller: UserBundle:Default:import}

afficher_import:
    path: /admin/afficherimport
    defaults: { _controller: UserBundle:Default:afficherImports}

supprimer_import:
    path: /admin/supprimerimport/{id}
    defaults: { _controller: UserBundle:Default:supprimerImports}

afficher_duplica:
    path: /admin/afficherduplica/{id}
    defaults: { _controller: UserBundle:Default:afficherDuplica}

importer_candidat:
    path: /admin/importer_candidat/{id}
    defaults: { _controller: UserBundle:Default:ImportCandidat}

fusionner_apprenant:
    path: /admin/fusion_apprenant/id_sas={sas}/id_user={user}
    defaults: { _controller: UserBundle:Default:Fusionner}


Afficher_Sas:
    path: /admin/affichageSAS/id={id}
    defaults: { _controller: UserBundle:Default:affichageSAS}

afficher_profil:
    path: /affichageProfil
    defaults: { _controller: UserBundle:Default:affichageProfil}

supprimer_Langue:
    path : /supprimerLangue/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:supprimerLangue}

supprimer_Hobbie:
    path : /supprimerHobbie/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:supprimerHobbie}

supprimer_Parent:
    path : /suppParent/id={id}
    defaults: { _controller: UserBundle:Default:suppParent}

parent_added:
    path: /AjouterParent
    defaults: { _controller: UserBundle:Default:AjouterParent}

supprimer_Experience:
    path : /suppExperience/id={id}
    defaults: { _controller: UserBundle:Default:suppExperience}

experience_added:
    path: /AjouterExperience
    defaults: { _controller: UserBundle:Default:AjouterExperience }

supprimer_Recommandation:
    path: /suppRecommandation/id={id}
    defaults: { _controller: UserBundle:Default:suppRecommandation}

recommandation_added:
    path: /AjouterRecommandation
    defaults: { _controller: UserBundle:Default:AjouterRecommandation}

supprimer_Diplome:
    path: /suppDiplome/id={id}
    defaults: { _controller: UserBundle:Default:suppDiplome}

diplome_added:
    path: /AjouterDiplome
    defaults: { _controller: UserBundle:Default:AjouterDiplome}

supprimer_Document:
    path: /suppDocument/id={id}
    defaults: { _controller: UserBundle:Default:suppDocument}

Document_added:
    path: /AjouterDocument
    defaults: { _controller: UserBundle:Default:AjouterDocument}

modifierStatut:
    path: /modifierStatutCandidature/id={id}/statut={statut}
    defaults: { _controller: UserBundle:Default:modifierStatutCandidature}

supprimer_Candidature:
    path: /suppCandidature/id={id}
    defaults: { _controller: UserBundle:Default:suppCandidature}

Candidature_added:
    path: /AjouterCandidature
    defaults: { _controller: UserBundle:Default:AjouterCandidature}

ajouter_Hobbie:
    path : /ajouterHobbie/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:ajouterHobbie}

ajouter_Langue:
    path : /ajouterLangue/id={id}/IdNiveau={IdNiveau}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:ajouterLangue}
