expired:
    path: /admin/expired/id={id}
    defaults: { _controller: UserBundle:Default:expired}

userModif:
    path: /userModif
    defaults: { _controller: UserBundle:Default:userModif}

metier_user_afficheUser:
    path: /admin/affichageUser/id={id}
    defaults: { _controller: UserBundle:Default:affichageUser}

user_added:
    path:  /admin/Useradded
    defaults: {_controller: UserBundle:Default:UserAdded}

supprimerUtilisateur:
    path : /admin/supprimeruser/id={id}
    defaults: { _controller: UserBundle:Default:supprimeruser}

import:
    path: /admin/import
    defaults: { _controller: UserBundle:Default:import}

afficher_import:
    path: /admin/afficherimport
    defaults: { _controller: UserBundle:Default:afficherImports}

supprimer_import:
    path: /admin/supprimerimport/{id}
    defaults: { _controller: UserBundle:Default:supprimerImports}

afficher_duplica:
    path: /admin/afficherduplica/{id}
    defaults: { _controller: UserBundle:Default:afficherDuplica}

importer_candidat:
    path: /admin/importer_SAStoUser/{id}
    defaults: { _controller: UserBundle:Default:SAStoUser}

fusionner_apprenant:
    path: /admin/fusion_apprenant/id_sas={sas}
    defaults: { _controller: UserBundle:Default:Fusionner}

afficher_profil:
    path: /affichageProfil
    defaults: { _controller: UserBundle:Default:affichageProfil}

supprimer_Langue:
    path : /supprimerLangue/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:supprimerLangue}

supprimer_Hobbie:
    path : /supprimerHobbie/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:supprimerHobbie}

supprimer_Parent:
    path : /suppParent/id={id}
    defaults: { _controller: UserBundle:Default:suppParent}

parent_added:
    path: /AjouterParent
    defaults: { _controller: UserBundle:Default:AjouterParent}

supprimer_Experience:
    path : /suppExperience/id={id}
    defaults: { _controller: UserBundle:Default:suppExperience}

experience_added:
    path: /AjouterExperience
    defaults: { _controller: UserBundle:Default:AjouterExperience }

supprimer_Recommandation:
    path: /suppRecommandation/id={id}
    defaults: { _controller: UserBundle:Default:suppRecommandation}

recommandation_added:
    path: /AjouterRecommandation
    defaults: { _controller: UserBundle:Default:AjouterRecommandation}

supprimer_Diplome:
    path: /suppDiplome/id={id}
    defaults: { _controller: UserBundle:Default:suppDiplome}

diplome_added:
    path: /AjouterDiplome
    defaults: { _controller: UserBundle:Default:AjouterDiplome}

supprimer_Document:
    path: /suppDocument/id={id}
    defaults: { _controller: UserBundle:Default:suppDocument}

Document_added:
    path: /AjouterDocument
    defaults: { _controller: UserBundle:Default:AjouterDocument}

modifierStatut:
    path: /modifierStatutCandidature/id={id}/statut={statut}
    defaults: { _controller: UserBundle:Default:modifierStatutCandidature}

supprimer_Candidature:
    path: /suppCandidature/id={id}
    defaults: { _controller: UserBundle:Default:suppCandidature}

Candidature_added:
    path: /AjouterCandidature
    defaults: { _controller: UserBundle:Default:AjouterCandidature}


ajouter_Hobbie:
    path : /ajouterHobbie/id={id}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:ajouterHobbie}

afficher_messagerie:
    path: /afficher_messagerie
    defaults: { _controller: UserBundle:Default:afficher_messagerie}

ajouter_Langue:
    path : /ajouterLangue/id={id}/IdNiveau={IdNiveau}/IdUser={IdUser}
    defaults: { _controller: UserBundle:Default:ajouterLangue}

reponseQCM:
    path: /reponseQCM/user={iduser}/reponse={idreponse}
    defaults: { _controller: UserBundle:Default:ReponseQCM }

MiseEnRelation_mission:
    path: /Miseenrelation/Mission/idDest={idDest}/idEnv={idEnv}/mission={mission}
    defaults: { _controller: UserBundle:MiseEnRelation:envoiMessageMR }


Reponse_Messagerie:
    path: /Messagerie/message={idmessage}
    defaults: { _controller: UserBundle:MiseEnRelation:RepondreMessage }

Postuler_Messagerie:
    path: /Messagerie/postuler/msg={idmessage}
    defaults: { _controller: UserBundle:MiseEnRelation:PostulerMessagerie }

apprenant_added:
    path: /ajouterApprenant
    defaults: { _controller: UserBundle:Default:ajouterApprenant}

show_Document:
    path: /DownloadDoc/iddoc={id}
    defaults: { _controller: UserBundle:Default:DownloadDoc}

Mise_En_Relation:
    resource: "@UserBundle/Resources/config/MiseEnRelationRouting.yml"
    prefix:   /MiseEnRelation

CompleterProfil:
    path: /CompleterProfil/IdUser={IdUser}
    defaults: {_controller: UserBundle:Default:CompleterProfil}

ChangerStatutApprenant:
    path: /ChangerStatutApprenant/IdUser={idUser}/statut={statut}
    defaults: {_controller: UserBundle:Default:ChangerStatutApprenant}

OrdreCompleterCR:
    path: /EmailRemplirCR/IdUser={idUser}/rdv={idRDV}
    defaults: {_controller: UserBundle:MiseEnRelation:envoiMailRemplirCR}

ConsulterCR:
    path: /ConsulterCR/rdv={idRDV}
    defaults: {_controller: UserBundle:MiseEnRelation:ConsulterCompteRendu}

ChangementRole:
    path: /ChangementRole/id={idUser}
    defaults: {_controller: UserBundle:Default:ChangementRole}

ModifAppSas:
    path: /ModifAppSas
    defaults: { _controller: UserBundle:Default:ModifAppSas}

afficher_import_rech:
    path: /afficher_import_rech/Nom={NomRech}/Ville={VilleRech}/Age={AgeRech}/Type={TypeRech}/Date={DateInscrip}
    defaults: { _controller: UserBundle:Default:afficherImportsRech}