expired:
    path: /admin/expired/id={id}
    defaults: { _controller: UserBundle:Default:expired}

userModif:
    path: /admin/userModif
    defaults: { _controller: UserBundle:Default:userModif}

metier_user_afficheUser:
    path: /admin/affichageUser/id={id}
    defaults: { _controller: UserBundle:Default:affichageUser}

user_added:
    path:  /admin/Useradded
    defaults: {_controller: UserBundle:Default:UserAdded}

supprimereUtilisateur:
    path : /admin/supprimeruser/id={id}
    defaults: { _controller: UserBundle:Default:supprimeruser}

modifierUser:
    path: /admin/modifierUtilisateur/{id}
    defaults: { _controller: UserBundle:Default:modifier}

import:
    path: /admin/import
    defaults: { _controller: UserBundle:Default:import}

afficher_import:
    path: /admin/afficherimport
    defaults: { _controller: UserBundle:Default:afficherImports}

supprimer_import:
    path: /admin/supprimerimport/{id}
    defaults: { _controller: UserBundle:Default:supprimerImports}

afficher_duplica:
    path: /admin/afficherduplica/{id}
    defaults: { _controller: UserBundle:Default:afficherDuplica}