ecole_admin:
    path:     /admin/Home/{ecole}
    defaults: { _controller: EcoleBundle:Default:loadAdmin }

ecole_admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: EcoleBundle:Default:affichageLicence}

loadconsulterQCM:
    path:     /consulterQCM/{id}
    defaults: { _controller: EcoleBundle:Default:loadQCM }
